---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars_prompt:
    - name: library
      prompt: Library name ?
      private: false
    
  tasks:
    
    - name: create {{ library }} library
      ibmi_cl_command:
        cmd: crtlib lib({{ library }})
        joblog: false
      register: crtlib_result
    - debug:
       var: crtlib_result
